name: alliance-geo

services:
  geo_backend_api:
    container_name: geo_backend_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      geo_postgres_db:
        condition: service_healthy
    networks:
      - geo-network

  geo_postgres_db:
    container_name: geo_postgres_db
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=geo_db
    ports:
      - "6666:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 1s
      retries: 100
    volumes:
      - geo_db-data:/var/lib/postgresql/data
    networks:
      - geo-network


volumes:
  geo_db-data:

networks:
  geo-network:
    driver: bridge