# Generated by Django 5.1.5 on 2025-01-22 15:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('antimeridian', models.BooleanField(default=False)),
            ],
        ),
    ]
