# Generated by Django 5.1.5 on 2025-01-25 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntersectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intersected_polygon_name', models.CharField(max_length=100)),
                ('coordinates', models.TextField()),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.polygonmodel')),
            ],
        ),
    ]
