# Generated by Django 5.1.5 on 2025-01-25 20:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_intersectionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intersectionmodel',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
